apply plugin: "java"

sourceSets.main.java.srcDirs = ["src"]

jar {
	archivesBaseName = 'forcex-windows-backend'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

task copyAssets(type: Copy) {
    from '../forcex/src/main/resources'
    into '../dist/windows/data'
}